name: C++ Build
permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup VS Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
    
    - name: Create build directory
      run: mkdir build
    
    - name: Install vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: '2023.10.19'
        
    - name: Install OpenSSL
      run: vcpkg install openssl:x64-windows
        
    - name: Compile C++ code
      run: |
        cl.exe /Zi /EHsc /DNDEBUG /nologo /std:c++17 /Zc:__cplusplus ^
        /Fe${{ github.workspace }}\build\app.exe ^
        ${{ github.workspace }}\src\*.cpp ^
        /I "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22621.0/um" ^
        /I "${{ github.workspace }}/vcpkg_installed/x64-windows/include" ^
        /link ^
        /LIBPATH:"${{ github.workspace }}/vcpkg_installed/x64-windows/lib" ^
        libcrypto.lib ^
        libssl.lib ^
        shell32.lib ^
        ole32.lib ^
        advapi32.lib
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: application
        path: ${{ github.workspace }}\build\*.exe
        if-no-files-found: error # Optional: 'warn', 'error', or 'ignore'
        retention-days: 30 # Optional: default is 90 days